[package]
name = "fibonacci_seq"
version = "0.1.0"
authors = ["TralahM <musyoki.tralah@students.jkuat.ac.ke>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
